### ISSUE TITLE
markdown body in dark mode

### ISSUE THREAD

**Issue by dxts** [RobbinBaauw/CSHub#122]
In dark mode the markdown body remains white and the dark-mode class changes text color also to white.

![image](https://user-images.githubusercontent.com/22395239/52066839-9f931d80-2579-11e9-837a-8c770a20720b.png)

**Comment by dxts** [comment]
```css
.theme--dark .cm-s-default {
    background-color: rgb(75, 75, 75);
}
```

is a decent fix i think
